### PR TITLE
Add LQR for computing optimal PID controller from Kv and Ka

### PR DESCRIPTION
**Pull request by calcmogul**
This is done by creating a model based on the dynamics Kv and Ka
represent, then finding an LQR for that model. The two terms in the
resulting K matrix are Kp and Kd for a PID controller.

I'm not sure how you want this integrated, so let me know. LQR can be tuned via the Q and R matrices, which represent acceptable error bounds and acceptable actuation effort respectively. A GUI that accepts values for that and shows the step response would be useful.

### CODE REVIEW

**Comment by calcmogul** [comment]
Here's a proof for the model. That probably belongs somewhere for internal documentation purposes.

```Given xdot = Ax + Bu where
x = [p]
    [v]
A = [0 1]
    [0 c]
B = [0]
    [b]
u_ff = K_v v + K_a a

Solve for c
-----------

If u = K_v v, then Ax + Bu = [v]
                             [0]

[0 1][p] + [0]          [v]
[0 c][v]   [b](K_v v) = [0]

cv + b K_v v = 0
cv = -b K_v v
c = -b K_v

Solve for b
-----------

If u = K_v v + K_a a, then Ax + Bu = xdot = [v]
                                            [a]

[0 1][p] + [0]                  [v]
[0 c][v]   [b](K_v v + K_a a) = [a]

cv + b(K_v v + K_a a) = a
cv + bK_v v + bK_a a = a
cv + bK_v v = a - bK_a a

Now substitute in equation for c and solve for b.

(-b K_v)v + bK_v v = a - bK_a a
-bK_v v + bK_v v = a - bK_a a
0 = a - bK_a a
bK_a a = a
b = a/(K_a a)
b = 1/K_a

Back-substitute for c
---------------------

c = -b K_v
c = -(1/K_a) K_v
c = -K_v/K_a

Therefore, the model is

       [0        1]  + [    0]
xdot = [0 -K_v/K_a]x   [1/K_a]u
```

**Comment by virtuald** [comment]
This seems useful. Do the dependencies you added all have published wheels for them and their requirements on pypi? I'd hate to make this harder to install for students without a compiler.

**Comment by auscompgeek** [comment]
It looks like both frccontrol and control (the only two dependencies being added) are pure-Python, so we're fine on that front.

**Comment by calcmogul** [comment]
I included frccontrol because the lqr() function I wrote there uses scipy. control's lqr() uses slycot and requires a Fortran compiler (slycot is optional and only needed for functions that use it).

**Comment by virtuald** [comment]
... so fortran is required for installation? Or not?

**Comment by calcmogul** [comment]
Fortran is required for using control's lqr() function. We're using frccontrol's lqr(), so we don't need Fortran.

**Comment by virtuald** [comment]
Sorry I've been so absent this summer. I'm happy to merge this if it's in a state to be merged (I see you pushed some commits 2 days ago).

**Comment by calcmogul** [comment]
@Oblarg is finishing up a GUI that'll supersede this.

**Comment by auscompgeek** [comment]
Looks like this ended up in #21.

**Pull request closed without merging**
