### PR TITLE
Add elevator characterization GUI

### PR DESCRIPTION
**Pull request by pietroglyph**
This PR finishes the work on the elevator characterization branch by adding the GUI and LQR that other mechanisms have. I haven't been able to test this with real data.

### CODE REVIEW

**Comment by Oblarg** [comment]
Can you update the readme to reflect the presence of the GUI, a la what's there for arm and drive?

**Comment by Oblarg** [comment]
Also, you shouldn't be committing the .gradlew files

**Comment by pietroglyph** [comment]
I've modified the elevator documentation to mention the GUI.

As for the gradle wrapper files, I committed those because [they're included with the examples for the other mechanisms](https://github.com/robotpy/robot-characterization/tree/master/arm-characterization/robot-java/gradle/wrapper). Should I still remove them?

**Comment by Oblarg** [comment]
Ah, you're right.  Leave them in, then.

Also, be sure to change the units to be appropriate for distance, rather than angle.

**Comment by pietroglyph** [comment]
@Oblarg I finally got some time to sit down and fix the units thing on this. This PR should be good to go unless you can spot any other bugs/problems.

**Comment by virtuald** [comment]
@Oblarg seems fine to me, feel free to merge

**Pull request merged**
